---
- name: Clone and Deploy Node.js App
  hosts: server2
  become: yes
  tasks:
    - name: make a directory
      ansible.builtin.file:
        path: /home/ubuntu/V1
        state: directory
        mode: '0755'
    - name: Copy V1 Artificats to Node 1
      ansible.builtin.copy:
        src: /home/runner/work/GH/GH/nodejs-applicationv1-1.0.0.tgz
        dest: /home/ubuntu/V1
        mode: '0644'
        follow: yes 
    - name: Extract the file
      ansible.builtin.unarchive:
        src: /home/ubuntu/V1/nodejs-applicationv1-1.0.0.tgz
        dest: /home/ubuntu/V1
        remote_src: yes
      become: yes
    - name: "Install nodejs"
      apt:
         update_cache: yes
         name: 
         - nodejs
         - npm
         state: present
    - name: Copy file with owner and permissions
      ansible.builtin.copy:
        src: /home/runner/work/GH/GH/abhishek/mynodejs.service
        dest: /etc/systemd/system/
        mode: '0644'
        follow: yes 
    
    - name: Enable service nodejs service
      command: "systemctl enable mynodejs"
      become: yes

    - name: Make sure a service unit is running
      command: "systemctl restart mynodejs"