name: Matrix
on: workflow_dispatch
jobs:
  build:
   strategy:
     matrix:
       node-version: [12,14,16]
       operating-system: [ubuntu-latest,windows-latest]
     runs-on: ${{ matrix.operating-system }}  
     steps:
       - name: Get code
         uses: actions/checkout@v3
       - name: node install
         uses: actions/setup-node@v3
         with:
           ${{ matrix.node-version }}
       - name: npm version
         run: npm version 
