name: version 1
on: push
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout 
      uses: actions/checkout@v3
    - name: Print workspace
      run: |
            ls ${{ github.workspace }}