name: version 1
on: push
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout 
      uses: actions/checkout@v3
    - name: Print workspace
      run: |
            ls ${{ github.workspace }}
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: install pip
      run: |
        python -m pip install --upgrade pip
        pip install ansible
    - name: perimission to RSA
      run: |
        chmod 400 /home/runner/work/GH/GH/key.pem
    - name: ping ansible
      run: |
        ansible server1 -i /home/runner/work/GH/GH/inventory.txt -m ping